# Generated by Django 2.2.3 on 2019-07-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('status', models.CharField(choices=[('unproccessed', 'Unprocessed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unproccessed', max_length=50)),
            ],
        ),
    ]
