# Generated by Django 2.2.3 on 2019-07-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='url',
            field=models.URLField(default='www.google.com', max_length=250),
            preserve_default=False,
        ),
    ]
