# Generated by Django 2.2.3 on 2019-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('unproccessed', 'Unprocessed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unproccessed', max_length=50),
        ),
    ]
